// This file is auto-generated by zRPC. Do not edit.
export const proto = `syntax = "proto3";
package zrpc;

message SayHelloRequest {
  string name = 1;
}

message SayHelloReply {
  string message = 1;
}

message GetUserRequest {
  string id = 1;
}

message GetUserReply {
  string id = 1;
  string name = 2;
  string email = 3;
}

service greeter {
  rpc sayHello (SayHelloRequest) returns (SayHelloReply);
}

service userService {
  rpc getUser (GetUserRequest) returns (GetUserReply);
}

`;
